### ISSUE TITLE
Seg. fault - not defined in both files

### ISSUE THREAD

**Issue by GuillemCabo** [veripool/vcddiff#2]
Hi, 
I'm testing this tool for the first time, and I found an issue with the first VCD file I tried. 
The VCD was generated by[ SBY ](https://github.com/YosysHQ/yosys), and GTKwave opens it fine. 

To reproduce:
[trace.zip](https://github.com/veripool/vcddiff/files/6765132/trace.zip)
```
./vcddiff trace.vcd trace.vcd
``` 
Note that I'm using a single VCD. I did this just to isolate problems. I would expect no differences.
This is the actual output:
```
WARNING - Ignoring signal smt_step (t) - not defined in both files
	  Defined in file 'trace.vcd' and not file 'trace.vcd'

WARNING - Ignoring signal smt_clock (!) - not defined in both files
	  Defined in file 'trace.vcd' and not file 'trace.vcd'

WARNING - Ignoring signal top.dut_pmu_ahb.inst_pmu_raw.inst_quota.smt_step (t) - not defined in both files
	  Defined in file 'trace.vcd' and not file 'trace.vcd'

WARNING - Ignoring signal top.dut_pmu_ahb.inst_pmu_raw.inst_quota.smt_clock (!) - not defined in both files
	  Defined in file 'trace.vcd' and not file 'trace.vcd'

Segmentation fault (core dumped)
``` 

OS info: 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by wsnyder** [comment]
Please note this repo was made to support Verilator's use of vcddiff for its self tests, but beyond that I don't think anyone is supporting vcddiff. Thus bugs like this are unlikely to be looked into by anyone.  Instead, I'd encourage you to debug it yourself, and hopefully you can determine a fix, which we'd welcome putting it into this repo.

**Comment by GuillemCabo** [comment]
Okay, thank you.
I let you know if I find a solution.
